---
project_name: golangci-lint

archives:
  - id: golangci-lint
    files:
      - LICENSE
    format: tar.gz
    name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      386: 32bit
      amd64: 64bit
      darwin: macOS
      linux: Linux

brews:
  - name: golangci-lint
    caveats:
    commit_author:
      name: Kamil Samigullin
      email: kamil@samigullin.info
    description: |
      golangci-lint is a fast Go linters runner. It runs linters in parallel,
      uses caching, supports yaml config, has integrations with all major IDE
      and has dozens of linters included.
    folder: Formula
    homepage: https://github.com/kamilsk/golangci-lint
    tap:
      owner: kamilsk
      name: homebrew-tap
    install: |
      bin.install "golangci-lint"
      prefix.install_metafiles
    test: |
      system "#{bin}/golangci-lint help"

builds:
  - id: golangci-lint
    binary: golangci-lint
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - 386
      - amd64
    goos:
      - darwin
      - linux
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    main: ./cmd/golangci-lint

changelog: { skip: true }

checksum: { name_template: checksums.txt }

release:
  github:
    owner: kamilsk
    name: golangci-lint
