#!/usr/bin/env bash

set -o nounset
set -o pipefail

function help() {
  echo "$0 <task> <args>"
  echo "Tasks:"
  compgen -A function | grep -v '^__' | sort | cat -n
}

function sync() {
  git fetch --all --prune --force
  git rebase upstream/master

  git tag --list \
  | grep -v '^v[0-9]' \
  | xargs -n1 git untag

  git branch -a \
  | grep -v upstream \
  | grep -v master \
  | grep -v HEAD \
  | grep -v extended \
  | awk -F '/' '{print $2" "$3}' \
  | xargs -n2 git push -d \$1 \$2

  git please
  open https://github.com/kamilsk/golangci-lint/releases
  open https://www.travis-ci.com/github/kamilsk/golangci-lint/builds
}

__default() { help; }

"${@:-__default}"
